[workspace]
members = [
    "transport",
    "examples/wasm-client",
    "examples/helloworld",
]

[patch.crates-io]
tonic = { git = "https://github.com/boxdot/tonic", rev = "2ed4144" }
tonic-build = { git = "https://github.com/boxdot/tonic", rev = "2ed4144" }
